### ISSUE TITLE
Clarifications on compute_distances() function

### ISSUE THREAD

**Issue by ghost** [vincentfpgarcia/kNN-CUDA#11]
Hello Vincent, 
Thank you for your work!

Could you please clarify a few things about your _compute_distances()_ function
that is used in the _knn_cuda_global_ implementation? Could you please clarify
how you specify conditions _cond0_ and _cond2_? As far as I understand, they are
used for staying within the A matrix when looping over the sub-matrices, but I
don’t fully understand how they are determined. For B matrix, as I
understood, _cond1= (begin_B + tx < query_width)_ is used to stay within the B
matrix in the X direction. However, you use both _cond0 = (begin_A + tx <ref_width)_ and _cond2 = (begin_A + ty < ref_width)_ to check if the index is
less than _ref_width_. Shouldn’t these conditions check that the x index is
less than _ref_width_ and the other index is less than the dimension of points?

Thank you in advance!

Best,
Ekaterina

**Comment by vincentfpgarcia** [comment]
I'm not surprised it confused you. I had to draw on the paper to verify my maths. After 11 years, I have to say that my memories were a bit fuzzy...

Let's say that we have `n_q` query points of dimension `d`. We can represent these points as a matrix of size `d x n_q` (height x width). Let's also consider `n_r` reference points of dimension `d` too (matrix of size `d x n_r`). When I compute the distance matrix, I end up with a matrix of size `n_r x n_q` (`n_r` is the height and `n_q` the width, just to be clear).
If I consider in CUDA one thread at position `(j,i)` in the distance matrix, I have to use one for loop on the j'th column of the reference matrix and one for loop on the i'th column of the query matrix.
But for 2 consecutive threads, the threads will loop on 2 consecutive columns in the query matrix but on the same column in the reference matrix. And that's how you loose efficiency!

Instead, I used shared memory to copy blocks of memories from both query and reference matrices. Then I loop over the shared memory where less penalty (maybe no penalty?) is applied when 2 threads read the same memory space.

That being said, let's say we have :
```
blockIdx.x = 2
blockIdx.y = 3
```
This means that we are going to iterate over:
- the 2nd column of blocks in the query matrix
- the 3rd column of blocks in the reference matrix

Let's consider a thread `(ty, tx) = (threadIdx.y, threadIdx.x)` in this block.

cond0: This thread can read in the reference memory only if it does not go too far outside horizontally:
```
blockIdx.y * BLOCK_DIM + tx < n_r
```
cond1: This thread can read in the query memory only if it does not go too far "right":
```
blockIdx.x * BLOCK_DIM + tx < n_q
```
That part was for reading reference and query matrices.


Now, we want to write in the output matrix of size `(n_r, n_q)`.
First, it should not go outside horizontally, which is again cond1.
Second, it should not go outside vertically, which is cond2:
```
blockIdx.y * BLOCK_DIM + ty < n_r
```

I hope this will help you understand what I have done.
If I had to write this code today, I'd make it more clear.
Sorry for that.
