### ISSUE TITLE
knn_cublas_with_indexes.cu failed to work 

### ISSUE THREAD

**Issue by hoding123** [vincentfpgarcia/kNN-CUDA#2]
environment:
cuda 7.5, win10, visual studio 2013

knn_cublas_with_indexes.cu failed to work.

I get the following errors:
MEMORY ALLOCATION ERROE: unspecfied launch time failure
Wished allocated memory:481024000

**Comment by Waszker** [comment]
Looks like you try to allocate more memory than your graphic card has. Is that right?

**Comment by hoding123** [comment]
Hi,

It runs well under Linux with Titan.

While, under windows, changing the query number will result in different
result(test with Titan Black and GTX 960 cuda 7.5). Sometimes I got this
error, but sometime it works. Note that it works with query number set to
30000, while fails when query number is set to 5000.
Block line

 // Computation of Q*transpose(R)
cublasSgemm('n', 't', (int)query_pitch, (int)ref_pitch, height,
(float)-2.0, query_dev, query_pitch, ref_dev, ref_pitch, (float)0.0,
dist_dev, query_pitch);

This error does not show any more. Of course it should not be blocked. And
the code always  run fine for the first iteration of the following code:
// Call kNN search CUDA
cudaEventRecord(start, 0);
for (i = 0; i < iterations; i++){
knn(ref, ref_nb, query, query_nb, dim, k, dist, ind);
}
However it fall in the following iteration.

2017-01-04 21:32 GMT+08:00 Piotr Waszkiewicz <notifications@github.com>:

**Comment by Waszker** [comment]
Have you tried to look for help on StackOverflow?
According to this [http://stackoverflow.com/questions/9901803/cuda-error-message-unspecified-launch-failure](url) 

> An unspecified launch failure is almost always a segfault. You've got an indexing mistake somewhere in your kernel, probably while accessing global memory.

**Comment by vincentfpgarcia** [comment]
I really need to update this code that was written using CUDA 1.2... 9 years ago !

**Comment by ghost** [comment]
@vincentfpgarcia Sir, I am also facing a problem on knn_cuda_with_indexes and other parts, I am using Matlab 2015b and 2016b with Cuda 7.0 version. I need this code for parallel processing using k nearest neighbor searching. Can you update this code or help me..
![error](https://user-images.githubusercontent.com/29269780/26913320-dced7bb6-4bce-11e7-82cd-73f9a296892e.jpg)
can you help me ??? I need this code in my master thesis...

**Comment by ayshaashraf9002** [comment]
![error2](https://user-images.githubusercontent.com/29269780/26913353-22caa5b4-4bcf-11e7-9a85-949b2a03c136.jpg) @vincentfpgarcia kindly check it and respond it. how i can improve it or removed the mex error. I think i am not properly giving arguments in mexcuda command. As my commands are...
setenv('MW_NVCC_PATH','C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin')
>> mexcuda '-LC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\lib\x64' -lnppi knn_cuda_with_indexes.cu

**Comment by vincentfpgarcia** [comment]
Hi,
The code has been written for CUDA 1.1 and nvmex of 2008.
I'm working on a newer version that should compile in CUDA 8.
I will update the CUDA code but not the MEX one.
Cheers,
Vincent

**Comment by ayshaashraf9002** [comment]
@vincentfpgarcia Sir, I am using GPU of Nvidia GTX 750 with intel core i5-3470 CPU 3.20GHz 
i am working on motion capture data set (MoCap) I want to increase the size of reference and query points from 65536 to larger value.  I can't understand these constants as I know we are taking the value of reference points in texture width. please guide  me how to modify block, grids and threads according to my specification
// Constants used by the program
#define MAX_PITCH_VALUE_IN_BYTES       262144
#define MAX_TEXTURE_WIDTH_IN_BYTES     65536
#define MAX_TEXTURE_HEIGHT_IN_BYTES    32768
#define MAX_PART_OF_FREE_MEMORY_USED   0.9
#define BLOCK_DIM                      16

According to my GPU GeForce GTX 750 Specifications: 
The Specification of our GPU is described below:
•	Total Global Memory: 2147483648
•	Total Shared Memory per block: 49152
•	Total Registers per block: 65536

•	Warp size: 32
•	Maximum memory pitch: 2147483647
•	Maximum threads per block: 1024

•	Maximum dimension 0 of block: 1024
•	Maximum dimension 1 of block: 1024
•	Maximum dimension 2 of block: 64

•	Maximum dimension 0 of grid: 2147483647
•	Maximum dimension 1 of grid: 65535
•	Maximum dimension 2 of grid: 65535

•	Clock rate: 1137000
•	Total constant memory: 65536
•	Texture alignment: 512

•	Concurrent copy and execution: yes
•	Numbers of multiprocessor: 4
•	Kernel execution timeout: yes

Can you please guide me how to utilize the Max GPU according to this code.

**Comment by ayshaashraf9002** [comment]
![result](https://user-images.githubusercontent.com/29269780/28259790-dcffc352-6a8c-11e7-8233-d8399b8cb078.jpg)
I want to increase the limit of reference and query points ... kindly help me in this aspect.

**Comment by ayshaashraf9002** [comment]
@vincentfpgarcia r u there ?? I need your help ... kindly reply me .

**Comment by ayshaashraf9002** [comment]
@vincentfpgarcia I want to ask some questions about your work kindly give me ur email id?

**Comment by vincentfpgarcia** [comment]
Have you read the paper going with the code ?
Most of your questions are answered I think.

**Comment by ayshaashraf9002** [comment]
Yes i read the paper thoroughly. Not just one time. Some of the constants
are not discussed in paper.

**Comment by ayshaashraf9002** [comment]
@vincentfpgarcia Sir i want to ask about data set size limitation issue, how can we increase the size of reference points. my 93 dimensions are properly working with this code but i want to increase the reference points as my data set frames are in millions. your code provides so efficient results on 65535 data set.

**Comment by ghost** [comment]
@vincentfpgarcia Sir i want to ask what is the purpose of iterations ?? why you are taking 10 or 100 iterations on knn_Cuda functions, is it to find the accuracy of results as you are dealing with random numbers and kindly describe me about the working of euclidean distance calculation kernal function using cuda. why we are using this function to calculate global and previous one texture distances
 global__ void cuComputeDistanceGlobal 
 i shall be very thankful to you if you answered my queries.

**Comment by aimansarfraz20** [comment]
I get the following errors:
MEMORY ALLOCATION ERROR: unspecified launch time failure
Whished allocated memory type Error
