### ISSUE TITLE
about reference points

### ISSUE THREAD

**Issue by ghost** [vincentfpgarcia/kNN-CUDA#3]
This code is helpful for beginners learning cuda, why we can't increase the limit...

**Comment by vincentfpgarcia** [comment]
I used cudaMallocPitch for optimal performances (compared to cudaMalloc).
The problem with this allocation is that you cannot allocate too many
points.
I don't know if this still applies with newer CUDA versions.
Check the documentation of cudaMallocPitch for more information.

**Comment by ghost** [comment]
Okay thanks i will check.

**Comment by ghost** [comment]
@vincentfpgarcia  Sire can you please describe me this term "#define MAX_PART_OF_FREE_MEMORY_USED   0.9" why used. what value i can update according to newer specification of  texture width, height[65536,65536] not older one.

#define MAX_PITCH_VALUE_IN_BYTES  =     262144  =>can replaced by Max 2D Linear Texture Pitch: 1048544 bytes/ Max Memory Pitch: 2147483647 bytes ????which one used how you decide to use 262144 this value

#define MAX_TEXTURE_WIDTH_IN_BYTES     65536  => same width
#define MAX_TEXTURE_HEIGHT_IN_BYTES    32768  => Max 2D Texture Size: 65536 x 65536
#define MAX_PART_OF_FREE_MEMORY_USED   0.9   ? how you decide it
#define BLOCK_DIM                      16

**Comment by vincentfpgarcia** [comment]
MAX_PART_OF_FREE_MEMORY_USED defines how much of the free memory available
the program is going to use for the computation. I wanted to make sure that
not all graphic memory is used by the program in order to avoid problems.

As I understand, you are using this code for your master project right ?
Please tell me what is your school, the master you're in and the name of
your professor(s) involved in this project.
Thank you.

**Comment by ghost** [comment]
Sir thanks 4 replying. i am learning the concepts of parallel processing
using cuda and mex file. Your work is bit helpful thatswhy i am asking all
these questions.

**Comment by ghost** [comment]
Sir i want to ask about openCl which one is more good in your point
of view. In CUDA i practice thrust library also. Its very good to use.

**Comment by vincentfpgarcia** [comment]
GitHub is not a forum. I've already answered many of your question.
You haven't answered mine. What is you school? Give me the name of your
advisors and a way to contact them.

**Comment by ghost** [comment]
Sir my work is different from this work. I am not using this for project.
Sorry for asking questions about open Cl and thurst here.

**Comment by aimansarfraz20** [comment]
I get the following errors:
MEMORY ALLOCATION ERROR: unspecified launch time failure
Whished allocated memory type Error
