### ISSUE TITLE
what is the 'ind' refer to?

### ISSUE THREAD

**Issue by SarKerson** [vincentfpgarcia/kNN-CUDA#4]
Thanks for your codes sharing.
But I still have some question when I use this.
I don't know what the 'ind' refer to in the file `'KNN.CUBLAS.with.indexes/knn_cublas_with_indexes.cu'.`
So I make some experiment, but all fail.
Such as, for this case:
`(Number of reference points      :   4096
Number of query points          :      1
Dimension of points             :    2
Number of neighbors to consider :    1
)`
And the ind is only one dim.

1. Is it the nth pair of point?  (means the point found is ref[ind[0] * 2, ind[0] * 2 + 1])
1. Or the position that fit to the query point? (means the point found is ref[ind[0] - 1, ind[0])

I would appriciate if you reply soon.

**Comment by vincentfpgarcia** [comment]
When you look for the k nearest neighbors, you might be either interested in the distances or in the points themselves. Sometimes, one might be only interested in the index of the k-th nearest neighbor. Here, indexes refer to the point themselves.
In your case, you have 4096 reference 2D points, and 1 query 2D point. The code is looking for the closest point from your query point among the reference points. As the consequence you will have 1 distance and 1 index.
