### ISSUE TITLE
Compatible to CUDA9.1?

### ISSUE THREAD

**Issue by Yumin-Sun-00** [vincentfpgarcia/kNN-CUDA#5]
is your package compatible to CUDA9.1, cuDNN7.1 on Ubuntu 16.04?

**Comment by waschbaer00** [comment]
BTW, your code only works for C? How about c++?

**Comment by vincentfpgarcia** [comment]
This code was compiling without errors in June 2017. I haven't updated it since then. But I guess it should work.
