### ISSUE TITLE
knn_cuda slower than C++ implementation

### ISSUE THREAD

**Issue by fferroni** [vincentfpgarcia/kNN-CUDA#6]
Hi,

I was trying to optimize some kNN query using cKDTree from Python scipy, which uses C++

```
import time
import numpy
from scipy.spatial import cKDTree

numpy.random.seed(0)
arr = numpy.random.rand(10000, 3).astype(numpy.float32)
ca  = numpy.arange(10000, dtype=numpy.uint32)

timings = []
for i in range(100):
    if i < 5: continue
    start = time.time()
    tree = cKDTree(arr)
    neighbors2 = tree.query(arr, 2)
    timings.append(time.time() - start)

print("Scipy:", numpy.mean(timings))
Scipy: 0.013833379745483399
```

However, if I use the same parameters in your test, it's slower for cuda.
```
PARAMETERS
- Number reference points : 10000
- Number query points     : 10000
- Dimension of points     : 3
- Number of neighbors     : 1

Ground truth computation in progress...

TESTS
- knn_c             : PASSED in  2.91740 seconds (averaged over   2 iterations)
- knn_cuda_global   : PASSED in  0.06941 seconds (averaged over 100 iterations)
- knn_cuda_texture  : PASSED in  0.05560 seconds (averaged over 100 iterations)
- knn_cublas        : ERROR: Unable to copy data from device to host

```

So the CUDA version is >5x slower. Also, I am unable to run knn_cublas.

**Comment by fferroni** [comment]
Also, I checked the implementation and you create an N^2 cost matrix, meaning that if you have millions of points, it would run out of memory, unlike cKDTree.
Are you aware of any implementations that are faster and as memory efficient? The same thing I observed using nanoflann. Much faster than this.

**Comment by vincentfpgarcia** [comment]
I have never pretended that the code I've written is the fastest implementation ever in every single use case. You have to understand the context of this project. Back in 2008, GPGPU was something very new and CUDA 1.1 (first public version) was just out. At that time, I've implemented this code that proved that using GPGPU could outperform classical C/C++ approaches on some use cases. It was not obvious back then. Now, everyone knows that GPU can be very useful, if not absolutely necessary, for some problems (e.g. training a huge neural network). 

There is no correct answer to the question _"What is the fastest implementation of kNN search problem?"_. It depends on the size of the data, on the dimension of the points, on the CPU and GPU used, if you have access to several GPUs, etc. For instance, when you use a kd-tree, you first need to build the tree, the you can find the k-NN using the tree structure. If the search using the tree is usually fast, building the tree itself can be quite slow. Sometimes you build the tree once for the entire program. Sometimes you have to rebuild the tree at every single iteration... So, depending on your problem, kd-tree might or might not be a very good fit. Another example. If you consider 100 reference points in 1D, only 1 query point and k=1, there's a good chance that using a simple C brut force approach will outperform by far the kd-tree approach (and k-NN CUDA) in both processing time and memory footprint.

Here is a part of the **Important note** section of the readme: _(...) The code was intended to provide a fast and generic solution to the challenging k-NN search problem. However, authors are well aware that for a very specific application (e.g. small number of points, small dimension, only one query point, etc.) there is often a better implementation either in terms of computation time or memory footprint. It is known that a GPGPU implementation should be adapted to the problem and to the specifications of the GPU used. This code will help one to identify if the GPGPU solution is viable for the given problem. Following the terms of the license below, one is allowed and should adapt the code._

**Comment by vincentfpgarcia** [comment]
What king of GPU are you using?
Could you please make the same test (using Python and k-NN CUDA) but for a dimension of 100 this time?
