### ISSUE TITLE
Tutorial needed.

### ISSUE THREAD

**Issue by NamLQ** [vincentfpgarcia/kNN-CUDA#9]
Hi!
Can you provide some command line examples? I can not figure out how to use your code.
Thank you very much!

**Comment by vgarcia-gpsw** [comment]
Hi,

Everything is explained in the read-me.

Compile the project using the Makefile:
- Open a command line tool or a terminal.
- Go to the code directory.
- Compile the code using the following command: `make`
- Test the code using the following command: `./test`

Best.

**Comment by vincentfpgarcia** [comment]
Hi,

Everything is explained in the read-me.

Compile the project using the Makefile:

- Open a command line tool or a terminal.
- Go to the code directory.
- Compile the code using the following command: `make`
- Test the code using the following command: `./test`

Best.

**Comment by NamLQ** [comment]
I would like to run my own data, save the indexes and the distances into csv files. How can I do that?

**Comment by RuABraun** [comment]
> Everything is explained in the read-me.

Is the point of your code just to run `./test`? Because that's the only thing you explain in the README.

**Comment by vincentfpgarcia** [comment]
The code provided in this repository is intended to be as general as possible. In your case, the best thing to do is to modify the test file as follow:

1. load your data from an external file (e.g. CSV, JSON, TXT, etc.)
2. run the k-NN algorithm
3. write the output into a CSV file

Good luck with your project!

**Comment by NamLQ** [comment]
I do not know the language of your source code, so it would be much useful if you can give me the complete codes, from loading .CSV input files (ref and query) to write the index and distance output files.

Thank you very much!

**Comment by vgarcia-gpsw** [comment]
As much as I would like to help you, I cannot provide code for your specific need. Otherwise I'll end up doing the homeworks of all computer science students across the world ;)
Good luck!

**Comment by NamLQ** [comment]
@vgarcia-gpsw and @vincentfpgarcia 

I am not a computer science student. I am a scientist working in biotechnology. I just know the R language and some very basic command lines. 
In R, I am using RANN package https://github.com/jefferis/RANN. It's slow for a large dataset, so I need a faster KNN library. To be able to use your library, maybe I need to invest a year to learn a new language or just a little help from the authors.

Thanks for your kind responses!
